# End-to-end smoke test against the live registry (not run by R CMD check).
library(datapond)
print(dp_list())
print(dp_info("eoir"))
con <- dp_connect("eoir")
print(DBI::dbGetQuery(con, "SELECT count(*) AS n FROM proceedings"))
print(head(dp_describe(con), 5))
print(dp_describe(con, search = "IDNCASE"))
dp_disconnect(con)
con <- dp_connect(c("dol-visas", "cms-medicare"), quiet = TRUE)
print(DBI::dbGetQuery(con, 'SELECT count(*) AS n FROM "cms-medicare".physician_summary'))
print(DBI::dbGetQuery(con, 'SELECT fiscal_year, count(*) AS n FROM "dol-visas".lca GROUP BY 1 ORDER BY 1 DESC LIMIT 3'))
dp_disconnect(con)
cat("SMOKE OK\n")
